name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Hvert 10. minutt
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: curl --silent --show-error --fail https://site3moterom3etg.onrender.com/ || true
